// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrjlzkimgdlozmwtenlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyamx6a2ltZ2Rsb3ptd3RlbmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Mjc0MjksImV4cCI6MjA2MTQwMzQyOX0.cRNfNz0I0En_DMEmGRPJJVZQZdVuzUcgUtqH7lUFGiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);